# Generated by Django 5.0.4 on 2024-09-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flavor', models.CharField(choices=[('vanilla', 'Vanilla'), ('chocolate', 'Chocolate'), ('strawberry', 'Strawberry'), ('mint', 'Mint'), ('cookie_dough', 'Cookie Dough'), ('other', 'Other')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
